/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AccountClass } from './account-class';
import { AccountType } from './account-type';
import { PaymentDetailsTypeRequest } from './payment-details-type-request';

/**
 * 
 * @export
 * @interface ACHDetailsRequestAllOf
 */
export interface ACHDetailsRequestAllOf {
    /**
     * 
     * @type {PaymentDetailsTypeRequest}
     * @memberof ACHDetailsRequestAllOf
     */
    'type': PaymentDetailsTypeRequest;
    /**
     * The routing number must follow proper format.
     * @type {string}
     * @memberof ACHDetailsRequestAllOf
     */
    'routing_number': string;
    /**
     * 
     * @type {string}
     * @memberof ACHDetailsRequestAllOf
     */
    'account_number': string;
    /**
     * 
     * @type {AccountType}
     * @memberof ACHDetailsRequestAllOf
     */
    'account_type': AccountType;
    /**
     * 
     * @type {AccountClass}
     * @memberof ACHDetailsRequestAllOf
     */
    'account_class': AccountClass;
    /**
     * 
     * @type {string}
     * @memberof ACHDetailsRequestAllOf
     */
    'beneficiary_name'?: string | null;
}

