/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AccountClass } from './account-class';
import { AccountType } from './account-type';
import { PaymentDetailsTypeResponse } from './payment-details-type-response';

/**
 * 
 * @export
 * @interface ACHDetailsResponseAllOf
 */
export interface ACHDetailsResponseAllOf {
    /**
     * 
     * @type {PaymentDetailsTypeResponse}
     * @memberof ACHDetailsResponseAllOf
     */
    'type': PaymentDetailsTypeResponse;
    /**
     * Payment Instrument ID that can be passed to the /transfers endpoint to trigger a transfer. The type of the payment instrument dictates the method. 
     * @type {string}
     * @memberof ACHDetailsResponseAllOf
     */
    'payment_instrument_id': string;
    /**
     * 
     * @type {string}
     * @memberof ACHDetailsResponseAllOf
     */
    'routing_number': string;
    /**
     * 
     * @type {string}
     * @memberof ACHDetailsResponseAllOf
     */
    'account_number': string;
    /**
     * 
     * @type {AccountType}
     * @memberof ACHDetailsResponseAllOf
     */
    'account_type'?: AccountType;
    /**
     * 
     * @type {AccountClass}
     * @memberof ACHDetailsResponseAllOf
     */
    'account_class'?: AccountClass;
}

