/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Balance } from './balance';
import { Money } from './money';

/**
 * 
 * @export
 * @interface BankConnectionAvailableBalance
 */
export interface BankConnectionAvailableBalance {
    /**
     * 
     * @type {Money}
     * @memberof BankConnectionAvailableBalance
     */
    'amount': Money;
    /**
     * 
     * @type {string}
     * @memberof BankConnectionAvailableBalance
     */
    'as_of_date': string;
}

