/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BankConnectionAvailableBalance } from './bank-connection-available-balance';
import { BankDetails } from './bank-details';

/**
 * 
 * @export
 * @interface BankConnection
 */
export interface BankConnection {
    /**
     * 
     * @type {string}
     * @memberof BankConnection
     */
    'id': string;
    /**
     * 
     * @type {BankDetails}
     * @memberof BankConnection
     */
    'bank_details'?: BankDetails;
    /**
     * Brex business account ID 
     * @type {string}
     * @memberof BankConnection
     */
    'brex_account_id'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof BankConnection
     */
    'last_four': string;
    /**
     * 
     * @type {BankConnectionAvailableBalance}
     * @memberof BankConnection
     */
    'available_balance'?: BankConnectionAvailableBalance;
    /**
     * 
     * @type {BankConnectionAvailableBalance}
     * @memberof BankConnection
     */
    'current_balance'?: BankConnectionAvailableBalance;
}

