/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BeneficiaryBankAddress } from './beneficiary-bank-address';

/**
 * 
 * @export
 * @interface BeneficiaryBank
 */
export interface BeneficiaryBank {
    /**
     * 
     * @type {string}
     * @memberof BeneficiaryBank
     */
    'name'?: string | null;
    /**
     * 
     * @type {BeneficiaryBankAddress}
     * @memberof BeneficiaryBank
     */
    'address'?: BeneficiaryBankAddress;
}

