/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CounterPartyType } from './counter-party-type';
import { Recipient } from './recipient';

/**
 * 
 * @export
 * @interface BookTransferDetailsAllOf
 */
export interface BookTransferDetailsAllOf {
    /**
     * 
     * @type {CounterPartyType}
     * @memberof BookTransferDetailsAllOf
     */
    'type': CounterPartyType;
    /**
     * 
     * @type {Recipient}
     * @memberof BookTransferDetailsAllOf
     */
    'recipient': Recipient;
}

