/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BookTransferDetailsResponseAllOf } from './book-transfer-details-response-all-of';
import { CounterPartyResponse } from './counter-party-response';
import { CounterPartyResponseType } from './counter-party-response-type';

/**
 * @type BookTransferDetailsResponse
 * @export
 */
export type BookTransferDetailsResponse = BookTransferDetailsResponseAllOf & CounterPartyResponse;


