/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BrexCashAccountDetailsResponseAllOf } from './brex-cash-account-details-response-all-of';
import { OriginatingAccountResponse } from './originating-account-response';
import { OriginatingAccountResponseType } from './originating-account-response-type';

/**
 * @type BrexCashAccountDetailsResponse
 * @export
 */
export type BrexCashAccountDetailsResponse = BrexCashAccountDetailsResponseAllOf & OriginatingAccountResponse;


