/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ReceivingAccountType } from './receiving-account-type';

/**
 * 
 * @export
 * @interface BrexCashDetailsAllOf
 */
export interface BrexCashDetailsAllOf {
    /**
     * 
     * @type {ReceivingAccountType}
     * @memberof BrexCashDetailsAllOf
     */
    'type': ReceivingAccountType;
    /**
     *  ID of the Brex business account: Can be found from the [List business accounts](https://developer.brex.com/openapi/payments_api/) endpoint 
     * @type {string}
     * @memberof BrexCashDetailsAllOf
     */
    'id': string;
}

