/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';
import { PaymentDetailsTypeResponse } from './payment-details-type-response';

/**
 * 
 * @export
 * @interface ChequeDetailsResponseAllOf
 */
export interface ChequeDetailsResponseAllOf {
    /**
     * 
     * @type {PaymentDetailsTypeResponse}
     * @memberof ChequeDetailsResponseAllOf
     */
    'type': PaymentDetailsTypeResponse;
    /**
     * Payment Instrument ID that can be passed to the /transfers endpoint to trigger a transfer. The type of the payment instrument dictates the method. 
     * @type {string}
     * @memberof ChequeDetailsResponseAllOf
     */
    'payment_instrument_id': string;
    /**
     * 
     * @type {Address}
     * @memberof ChequeDetailsResponseAllOf
     */
    'mailing_address': Address;
    /**
     * 
     * @type {string}
     * @memberof ChequeDetailsResponseAllOf
     */
    'recipient_name': string;
}

