/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CounterPartyResponseType } from './counter-party-response-type';
import { VendorDetailsResponse } from './vendor-details-response';

/**
 * @type CounterPartyResponse
 * Counterparty Details for the transfer - Currently only supports vendors that are returned in the  response from the /vendors endpoint BOOK_TRANSFER is a limited feature. Please reach out if you are interested.     
 * @export
 */
export type CounterPartyResponse = { type: 'BANK_ACCOUNT' } & BankAccountDetailsResponse | { type: 'BOOK_TRANSFER' } & BookTransferDetailsResponse | { type: 'VENDOR' } & VendorDetailsResponse;


