/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CounterPartyIncomingTransferType } from './counter-party-incoming-transfer-type';

/**
 * 
 * @export
 * @interface CounterPartyBankDetailsAllOf
 */
export interface CounterPartyBankDetailsAllOf {
    /**
     * 
     * @type {CounterPartyIncomingTransferType}
     * @memberof CounterPartyBankDetailsAllOf
     */
    'type': CounterPartyIncomingTransferType;
    /**
     *  The financial account id: Can be found from the [List linked accounts](https://developer.brex.com/openapi/payments_api/) endpoint 
     * @type {string}
     * @memberof CounterPartyBankDetailsAllOf
     */
    'id': string;
}

