/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CounterPartyBankDetailsAllOf } from './counter-party-bank-details-all-of';
import { CounterPartyIncomingTransfer } from './counter-party-incoming-transfer';
import { CounterPartyIncomingTransferType } from './counter-party-incoming-transfer-type';

/**
 * @type CounterPartyBankDetails
 * @export
 */
export type CounterPartyBankDetails = CounterPartyBankDetailsAllOf & CounterPartyIncomingTransfer;


