/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BookTransferDetails } from './book-transfer-details';
import { CounterPartyType } from './counter-party-type';
import { Recipient } from './recipient';
import { VendorDetails } from './vendor-details';

/**
 * @type CounterParty
 * Counterparty Details for the transfer
 * @export
 */
export type CounterParty = { type: 'BOOK_TRANSFER' } & BookTransferDetails | { type: 'VENDOR' } & VendorDetails;


