/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CounterPartyIncomingTransfer } from './counter-party-incoming-transfer';
import { Money } from './money';
import { ReceivingAccount } from './receiving-account';

/**
 * 
 * @export
 * @interface CreateIncomingTransferRequest
 */
export interface CreateIncomingTransferRequest {
    /**
     *   Description of the transfer for internal use. Not exposed externally.  
     * @type {string}
     * @memberof CreateIncomingTransferRequest
     */
    'description': string;
    /**
     * 
     * @type {CounterPartyIncomingTransfer}
     * @memberof CreateIncomingTransferRequest
     */
    'counterparty': CounterPartyIncomingTransfer;
    /**
     * 
     * @type {ReceivingAccount}
     * @memberof CreateIncomingTransferRequest
     */
    'receiving_account': ReceivingAccount;
    /**
     * 
     * @type {Money}
     * @memberof CreateIncomingTransferRequest
     */
    'amount': Money;
}

