/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';
import { PaymentDetailsTypeRequest } from './payment-details-type-request';

/**
 * 
 * @export
 * @interface DomesticWireDetailsRequestAllOf
 */
export interface DomesticWireDetailsRequestAllOf {
    /**
     * 
     * @type {PaymentDetailsTypeRequest}
     * @memberof DomesticWireDetailsRequestAllOf
     */
    'type': PaymentDetailsTypeRequest;
    /**
     * The routing number must follow proper format.
     * @type {string}
     * @memberof DomesticWireDetailsRequestAllOf
     */
    'routing_number': string;
    /**
     * 
     * @type {string}
     * @memberof DomesticWireDetailsRequestAllOf
     */
    'account_number': string;
    /**
     * 
     * @type {Address}
     * @memberof DomesticWireDetailsRequestAllOf
     */
    'address': Address;
    /**
     * 
     * @type {string}
     * @memberof DomesticWireDetailsRequestAllOf
     */
    'beneficiary_name'?: string | null;
}

