/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AccountClass } from './account-class';
import { AccountType } from './account-type';
import { Address } from './address';
import { DomesticWireDetailsRequestAllOf } from './domestic-wire-details-request-all-of';
import { PaymentAccountDetails } from './payment-account-details';
import { PaymentDetailsTypeRequest } from './payment-details-type-request';

/**
 * @type DomesticWireDetailsRequest
 * @export
 */
export type DomesticWireDetailsRequest = DomesticWireDetailsRequestAllOf & PaymentAccountDetails;


