/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Address } from './address';
import { PaymentDetailsTypeResponse } from './payment-details-type-response';

/**
 * 
 * @export
 * @interface InternationalWireDetailsResponseAllOf
 */
export interface InternationalWireDetailsResponseAllOf {
    /**
     * 
     * @type {PaymentDetailsTypeResponse}
     * @memberof InternationalWireDetailsResponseAllOf
     */
    'type': PaymentDetailsTypeResponse;
    /**
     * Payment Instrument ID that can be passed to the /transfers endpoint to trigger a transfer. The type of the payment instrument dictates the method. 
     * @type {string}
     * @memberof InternationalWireDetailsResponseAllOf
     */
    'payment_instrument_id': string;
    /**
     * Counterparty\'s `SWIFT` code
     * @type {string}
     * @memberof InternationalWireDetailsResponseAllOf
     */
    'swift_code': string;
    /**
     * Counterparty\'s international bank account number
     * @type {string}
     * @memberof InternationalWireDetailsResponseAllOf
     */
    'iban': string;
    /**
     * Name of counterparty\'s bank
     * @type {string}
     * @memberof InternationalWireDetailsResponseAllOf
     */
    'beneficiary_bank_name'?: string | null;
    /**
     * 
     * @type {Address}
     * @memberof InternationalWireDetailsResponseAllOf
     */
    'address': Address;
}

