/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { BrexCashAccountDetails } from './brex-cash-account-details';
import { OriginatingAccountType } from './originating-account-type';

/**
 * @type OriginatingAccount
 * Originating account details for the transfer
 * @export
 */
export type OriginatingAccount = { type: 'BREX_CASH' } & BrexCashAccountDetails;


