/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ACHDetailsResponse } from './achdetails-response';
import { AccountClass } from './account-class';
import { AccountType } from './account-type';
import { Address } from './address';
import { ChequeDetailsResponse } from './cheque-details-response';
import { DomesticWireDetailsResponse } from './domestic-wire-details-response';
import { InternationalWireDetailsResponse } from './international-wire-details-response';
import { PaymentDetailsTypeResponse } from './payment-details-type-response';

/**
 * @type PaymentAccountDetailsResponse
 * @export
 */
export type PaymentAccountDetailsResponse = { type: 'ACH' } & ACHDetailsResponse | { type: 'CHEQUE' } & ChequeDetailsResponse | { type: 'DOMESTIC_WIRE' } & DomesticWireDetailsResponse | { type: 'INTERNATIONAL_WIRE' } & InternationalWireDetailsResponse;


