/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ACHDetailsRequest } from './achdetails-request';
import { AccountClass } from './account-class';
import { AccountType } from './account-type';
import { Address } from './address';
import { ChequeDetailsRequest } from './cheque-details-request';
import { DomesticWireDetailsRequest } from './domestic-wire-details-request';
import { PaymentDetailsTypeRequest } from './payment-details-type-request';

/**
 * @type PaymentAccountDetails
 * Payment Instruments associated with the vendor. Each vendor can only have one payment account per payment instrument type. For instance, a vendor may have associated details for each of ACH, DOMESTIC_WIRE, and CHEQUE, but they cannot have 2 entries for ACH. If you modify a vendor\'s existing payment instrument type with new details, it will overwrite any previous data. 
 * @export
 */
export type PaymentAccountDetails = { type: 'ACH' } & ACHDetailsRequest | { type: 'CHEQUE' } & ChequeDetailsRequest | { type: 'DOMESTIC_WIRE' } & DomesticWireDetailsRequest;


