/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { RecipientType } from './recipient-type';

/**
 * 
 * @export
 * @interface Recipient
 */
export interface Recipient {
    /**
     * Specifies the type of the recipient.  `ACCOUNT_ID` is the ID of a Brex Business account. `PAYMENT_INSTRUMENT_ID` is the ID of Payment Instrument of the receiving Brex account. 
     * @type {RecipientType}
     * @memberof Recipient
     */
    'type': RecipientType;
    /**
     * 
     * @type {string}
     * @memberof Recipient
     */
    'id': string;
}

