/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * `PROCESSING`: We have started to process the sending or receiving of this transaction. `SCHEDULED`: The transaction is scheduled to enter the `PROCESSING` status. `PENDING_APPROVAL`: The transaction requires approval before it can enter the `SCHEDULED` or `PROCESSING` status. `FAILED`: A grouping of multiple terminal states that prevented the transaction from completing. This includes a a user-cancellation, approval being denied, insufficient funds, failed verifications, etc. `PROCESSED`: The money movement has been fully completed, which could mean money sent has arrived. 
 * @export
 * @enum {string}
 */
export type TransferStatus = 'PROCESSING' | 'SCHEDULED' | 'PENDING_APPROVAL' | 'FAILED' | 'PROCESSED'

