/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * `USER_CANCELLED`: The transfer was canceled. `INSUFFICIENT_FUNDS`: The transfer could not be sent due to insufficient funds. `APPROVAL_DENIED`: The transfer was not sent because it was denied. `BLOCKED_BY_POSITIVE_PAY`: The transfer was blocked because of the ACH debit settings. 
 * @export
 * @enum {string}
 */
export type TransferCancellationReason = 'USER_CANCELLED' | 'INSUFFICIENT_FUNDS' | 'APPROVAL_DENIED' | 'BLOCKED_BY_POSITIVE_PAY'

