/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Money } from './money';
import { OriginatingAccountResponse } from './originating-account-response';
import { PaymentType } from './payment-type';
import { TransferCancellationReason } from './transfer-cancellation-reason';
import { TransferCounterparty } from './transfer-counterparty';
import { TransferStatus } from './transfer-status';

/**
 * 
 * @export
 * @interface Transfer
 */
export interface Transfer {
    /**
     * Description of the transfer
     * @type {string}
     * @memberof Transfer
     */
    'description'?: string | null;
    /**
     * Unique ID associated with the transfer
     * @type {string}
     * @memberof Transfer
     */
    'id': string;
    /**
     * 
     * @type {TransferCounterparty}
     * @memberof Transfer
     */
    'counterparty'?: TransferCounterparty;
    /**
     * 
     * @type {PaymentType}
     * @memberof Transfer
     */
    'payment_type': PaymentType;
    /**
     * 
     * @type {Money}
     * @memberof Transfer
     */
    'amount': Money;
    /**
     * Transaction processing date
     * @type {string}
     * @memberof Transfer
     */
    'process_date'?: string | null;
    /**
     * 
     * @type {OriginatingAccountResponse}
     * @memberof Transfer
     */
    'originating_account': OriginatingAccountResponse;
    /**
     * `PROCESSING`: We have started to process the sending or receiving of this transaction. `SCHEDULED`: The transaction is scheduled to enter the `PROCESSING` status. `PENDING_APPROVAL`: The transaction requires approval before it can enter the `SCHEDULED` or `PROCESSING` status. `FAILED`: A grouping of multiple terminal states that prevented the transaction from completing. This includes a a user-cancellation, approval being denied, insufficient funds, failed verifications, etc. `PROCESSED`: The money movement has been fully completed, which could mean money sent has arrived. 
     * @type {TransferStatus}
     * @memberof Transfer
     */
    'status': TransferStatus;
    /**
     * 
     * @type {TransferCancellationReason}
     * @memberof Transfer
     */
    'cancellation_reason'?: TransferCancellationReason;
    /**
     * Estimated delivery date for transfer
     * @type {string}
     * @memberof Transfer
     */
    'estimated_delivery_date'?: string | null;
    /**
     * User ID of the transfer initiator
     * @type {string}
     * @memberof Transfer
     */
    'creator_user_id'?: string | null;
    /**
     * Date of transfer creation
     * @type {string}
     * @memberof Transfer
     */
    'created_at'?: string | null;
    /**
     * Human readable name for the transaction
     * @type {string}
     * @memberof Transfer
     */
    'display_name'?: string | null;
    /**
     * External memo for the transfer. `Payment Instructions` for Wires and the `Entry Description` for ACH payments.  Must be at most 90 characters for `ACH` and `WIRE` transactions and at most 40 characters for `CHEQUES` 
     * @type {string}
     * @memberof Transfer
     */
    'external_memo'?: string | null;
}

