/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CounterPartyResponse } from './counter-party-response';
import { CounterPartyResponseType } from './counter-party-response-type';
import { VendorDetailsResponseAllOf } from './vendor-details-response-all-of';

/**
 * @type VendorDetailsResponse
 * @export
 */
export type VendorDetailsResponse = CounterPartyResponse & VendorDetailsResponseAllOf;


