/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CounterPartyType } from './counter-party-type';

/**
 * 
 * @export
 * @interface VendorDetailsAllOf
 */
export interface VendorDetailsAllOf {
    /**
     * 
     * @type {CounterPartyType}
     * @memberof VendorDetailsAllOf
     */
    'type': CounterPartyType;
    /**
     * ID of the vendor\'s payment instrument: this will dictate the payment method and the counterparty of the transaction. The payment instrument ID is returned from the /vendors response and the type of the instrument will dictate the payment method. eg. Passing an instrument ID of type ACH will trigger an ACH payment to the associated vendor. Since a payment instrument can be updated while retaining the same payment_instrument_id,  please make sure to double check the details. 
     * @type {string}
     * @memberof VendorDetailsAllOf
     */
    'payment_instrument_id': string;
}

