/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaymentAccountResponse } from './payment-account-response';

/**
 * 
 * @export
 * @interface VendorResponse
 */
export interface VendorResponse {
    /**
     * Vendor ID: Can be passed to /transfers endpoint to specify counterparty. 
     * @type {string}
     * @memberof VendorResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof VendorResponse
     */
    'company_name'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VendorResponse
     */
    'email'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VendorResponse
     */
    'phone'?: string | null;
    /**
     * 
     * @type {Array<PaymentAccountResponse>}
     * @memberof VendorResponse
     */
    'payment_accounts'?: Array<PaymentAccountResponse> | null;
}

