/*
Payments API


The payments API allows you to initiate and manage payments and vendors from your Brex business accounts.


The version of the OpenAPI document: 1.0
Contact: developer-access@brex.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CounterPartyResponseType } from './counter-party-response-type';

/**
 * 
 * @export
 * @interface VendorDetailsResponseAllOf
 */
export interface VendorDetailsResponseAllOf {
    /**
     * 
     * @type {CounterPartyResponseType}
     * @memberof VendorDetailsResponseAllOf
     */
    'type': CounterPartyResponseType;
    /**
     * 
     * @type {string}
     * @memberof VendorDetailsResponseAllOf
     */
    'payment_instrument_id': string;
    /**
     * Vendor ID returned from `/vendors` endpoint
     * @type {string}
     * @memberof VendorDetailsResponseAllOf
     */
    'id': string;
    /**
     * Routing number of a bank account (or SWIFT/BIC code for international transfer).
     * @type {string}
     * @memberof VendorDetailsResponseAllOf
     */
    'routing_number'?: string | null;
    /**
     * Account number of a bank account (or IBAN code for international transfer).
     * @type {string}
     * @memberof VendorDetailsResponseAllOf
     */
    'account_number'?: string | null;
}

